# Generated by Django 3.1.4 on 2020-12-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotrapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposalItem_category', to='quotrapi.category'),
        ),
    ]
