# Generated by Django 3.1.4 on 2020-12-15 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotrapi', '0002_auto_20201213_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposals', to='quotrapi.customer'),
        ),
    ]
