# Generated by Django 3.1.4 on 2020-12-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotrapi', '0003_auto_20201215_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='proposals', to='quotrapi.quotruser'),
        ),
    ]
