# Generated by Django 3.1.4 on 2020-12-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotrapi', '0004_auto_20201216_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_accessory', to='quotrapi.item'),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotrapi.proposal'),
        ),
    ]
