# Generated by Django 3.1.4 on 2020-12-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotrapi', '0005_auto_20201223_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='quotrapi.item'),
        ),
    ]
