# Generated by Django 3.1.4 on 2020-12-28 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotrapi', '0006_auto_20201223_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_path',
            field=models.ImageField(null=True, upload_to='items'),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalitems', to='quotrapi.item'),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalitems', to='quotrapi.proposal'),
        ),
    ]
