# Generated by Django 3.1.4 on 2020-12-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotrapi', '0007_auto_20201228_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='quotruser',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='quotruser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='quotrusers'),
        ),
    ]
